### PR TITLE
Bgs

### PR DESCRIPTION
**Pull request by abughalib**
What?
Added Influence Chart
image

### CODE REVIEW

**Review by AshAman999 — COMMENTED** [review]
If i understood clearly, this interaction chart is to keep in check the trend behavior of the players, which maps the use >? sort of something similar?

**Comment by abughalib** [comment]
> If i understood clearly, this interaction chart is to keep in check the trend behavior of the players, which maps the use >? sort of something similar?

Somewhat similar, It plots the influence made by players on a particular star system, the habituated ones.

**Comment by AshAman999** [comment]
In that case i would suggest you to store the data somewhere like maybe local storage or mongodb clusters

**Comment by abughalib** [comment]
> In that case i would suggest you to store the data somewhere like maybe local storage or mongodb clusters

It doesn't need to be stored, I'm using API to get these data and for the Chart as well.

**Review by AshAman999 — APPROVED** [review]
I'm not sure but committing pub-spec.lock is a good idea

**Pull request merged**
